name = "Match"
uuid = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
version = "2.4.1"
authors = ["Neal Gafter <neal@gafter.com>", "Nate Nystrom <nate.nystrom@relational.ai>", "Kevin Squire <kevin.squire@gmail.com>"]

[deps]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"

[compat]
MacroTools = "0.4, 0.5"
OrderedCollections = "1"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
